name: catalog_chooser
description: A new Flutter project.

version: 0.2.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^4.3.2
  flutter_riverpod: ^0.12.0
  flutter_state_notifier: ^0.4.2
  freezed_annotation: ^0.12.0
  state_notifier: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.10.7

flutter:
  uses-material-design: true