name: catalog_chooser
description: A new Flutter project.

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.7.1
  provider: ^4.1.0-dev+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  freezed: ^0.10.7

flutter:
  uses-material-design: true